language: python

python:
  - "3.3"

install:
  - pip install pylint coverage coveralls

script:
  - pylint gist
  #- coverage run -m unittest -v
  - nosetests -v --with-coverage

after_success:
  - coveralls

notifications:
  email: false
